1105
mathina-eu/mathina pull request #57
Opened 2021-05-11 15:15 UTC by somlyody

2021-05-11 22:13 UTC, SevenIndirecto requested changes

2021-05-11 22:18 UTC, SevenIndirecto commented on src/hub/i18n/en.js
> +    first policeman: 'First policeman'
Also even if we added the characters like this, they can't have spaces for 'keys'. So it needs to be something like:
```
first_policeman: 'First policeman'
```

2021-05-12 07:22 UTC, somlyody commented on src/hub/i18n/en.js
> +    first policeman: 'First policeman'
hello, these have their own dialog portraits but they appear only in the Logi-city stories. which are the generic characters?

2021-05-12 10:16 UTC, SevenIndirecto commented on src/hub/i18n/en.js
> +    first policeman: 'First policeman'
Hey, I guess this is fine, just please change to using keys without spaces: ('keys' are the values on the left side of the `:`)

```
firstPoliceman: 'First policeman'
```

2021-05-14 07:35 UTC, rmoschetti commented
Since there are some conflicts, and also some new changes in the branch, I'll close this and reopen a new one with all the corrections.

2021-05-14 07:35 UTC, closed without merging